# Generated by Django 5.0.6 on 2024-07-19 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ElPeuco', '0004_carrito_carritoitem'),
    ]

    operations = [
        migrations.CreateModel(
            name='Apedido',
            fields=[
                ('id_pedido', models.AutoField(primary_key=True, serialize=False)),
                ('Correo_pedido', models.EmailField(max_length=254)),
                ('Titulo_Pedido', models.CharField(max_length=60)),
                ('descripcion_pedido', models.TextField()),
                ('Imagen_Adjunta', models.ImageField(upload_to='images/')),
            ],
        ),
    ]
